PipelineSecrets:
  DockerConfig: '{"auths":{"uwdcicdopt.azurecr.io":{"auth":"dXdkY2ljZG9wdDpPYWRteW4xN1NpbzgvazU4aTFUUjZodUNxUkxvZ3hBNQ=="}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: opentest.run
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: uwdcicdopt.azurecr.io
        TILLER_NAMESPACE: kube-system
prow: {}
